
.PHONY : target clean $(PHONYS)

target : $(TARGET)

include Makefile.complie

$(TARGET) : $(TARGET_OBJS)
	@echo 'AR $@'
	$(Q)$(AR) cqs $@ $(TARGET_OBJS)

clean :
	@echo 'CLEAN $(WD)'
	$(Q)$(RM) $(TARGET) $(TARGET_OBJS)

